# 빌드 환경 설정
FROM gradle:7.6-jdk17

# 작업 디렉토리 설정
WORKDIR /app

# Gradle 빌드 파일과 소스 코드 복사
COPY build.gradle settings.gradle .
COPY src ./src

# Gradle을 사용하여 애플리케이션 빌드
RUN gradle clean build --no-daemon

# 빌드된 JAR 파일을 실행 환경으로 복사
RUN cp /app/build/libs/*-SNAPSHOT.jar ./app.jar

# 빌드된 JAR 파일 실행
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]