version: '3'
services:
  spring-backend:
    build: ./
    image: junghunlim0707/spring-cicd:latest
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
    restart: on-failure
