name: Spring Build and Docker push

on:
  push:
    branches:
      - 03-cicd

jobs:
  Spring-Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./demo-cicd/Dockerfile
          push: true
          # github.sha: 이미지의 소스코드 변경사항을 의미하는 커밋의 아이디를 이미지의 테그에 추가
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-cicd:${{ github.sha }}
          platforms: linux/amd64,linus/arm64
